/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type DirectionType = { 'up' : null } |
  { 'down' : null };
export interface MarketData {
  'direction' : DirectionType,
  'volume' : number,
  'price' : number,
  'symbol' : string,
}
export interface MarketSnapshot {
  'binanceTrades' : MarketSourceResult,
  'coingeckoBTC' : MarketSourceResult,
}
export interface MarketSourceResult {
  'ok' : boolean,
  'body' : string,
  'errorMessage' : [] | [string],
}
export type Theme = { 'darkNeon' : null } |
  { 'cyberGlow' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UnifiedSnapshot {
  'marketData' : Array<MarketData>,
  'timestamp' : bigint,
}
export interface UserPreferences {
  'theme' : Theme,
  'language' : string,
  'favourites' : Array<MarketData>,
  'enableAlerts' : boolean,
}
export interface UserPreferencesInput {
  'theme' : Theme,
  'user' : Principal,
  'language' : string,
  'favourites' : Array<MarketData>,
  'enableAlerts' : boolean,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'configurePollingIntervals' : ActorMethod<[bigint, bigint], undefined>,
  'fetchAssetData' : ActorMethod<[string], [] | [MarketData]>,
  'fetchAssetList' : ActorMethod<[], Array<string>>,
  'fetchBinanceFuturesAssets' : ActorMethod<[], [] | [UnifiedSnapshot]>,
  'filterAssetsByDirection' : ActorMethod<[DirectionType], Array<MarketData>>,
  'getBinanceTradesBTCUSDT' : ActorMethod<[], string>,
  'getCoinGeckoBTC' : ActorMethod<[], string>,
  'getCryptoMarketSnapshot' : ActorMethod<[], MarketSnapshot>,
  'getUserPreferences' : ActorMethod<[Principal], [] | [UserPreferences]>,
  'getUserPreferencesWithPreferences' : ActorMethod<
    [Principal],
    [] | [UserPreferences]
  >,
  'recordAssetData' : ActorMethod<[MarketData], undefined>,
  'setUserPreferences' : ActorMethod<[UserPreferencesInput], UserPreferences>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];