/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DirectionType = IDL.Variant({
  'up' : IDL.Null,
  'down' : IDL.Null,
});
export const MarketData = IDL.Record({
  'direction' : DirectionType,
  'volume' : IDL.Float64,
  'price' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const UnifiedSnapshot = IDL.Record({
  'marketData' : IDL.Vec(MarketData),
  'timestamp' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'notificationsEnabled' : IDL.Bool,
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const MarketSourceResult = IDL.Record({
  'ok' : IDL.Bool,
  'body' : IDL.Text,
  'errorMessage' : IDL.Opt(IDL.Text),
});
export const MarketSnapshot = IDL.Record({
  'binanceSpotTicker' : MarketSourceResult,
  'binanceTrades' : MarketSourceResult,
  'binanceSpotDepth' : MarketSourceResult,
  'coingeckoBTC' : MarketSourceResult,
});
export const Theme = IDL.Variant({
  'darkNeon' : IDL.Null,
  'cyberGlow' : IDL.Null,
});
export const UserPreferences = IDL.Record({
  'theme' : Theme,
  'language' : IDL.Text,
  'favourites' : IDL.Vec(MarketData),
  'enableAlerts' : IDL.Bool,
});
export const UserPreferencesInput = IDL.Record({
  'theme' : Theme,
  'user' : IDL.Principal,
  'language' : IDL.Text,
  'favourites' : IDL.Vec(MarketData),
  'enableAlerts' : IDL.Bool,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'configurePollingIntervals' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'fetchAssetData' : IDL.Func([IDL.Text], [IDL.Opt(MarketData)], ['query']),
  'fetchAssetList' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'fetchBinanceFuturesAssets' : IDL.Func(
      [],
      [IDL.Opt(UnifiedSnapshot)],
      ['query'],
    ),
  'filterAssetsByDirection' : IDL.Func(
      [DirectionType],
      [IDL.Vec(MarketData)],
      ['query'],
    ),
  'getBinanceSpotDepthBTCUSDT' : IDL.Func([], [IDL.Text], []),
  'getBinanceSpotTickerBTCUSDT' : IDL.Func([], [IDL.Text], []),
  'getBinanceTradesBTCUSDT' : IDL.Func([], [IDL.Text], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCoinGeckoBTC' : IDL.Func([], [IDL.Text], []),
  'getCryptoMarketSnapshot' : IDL.Func([], [MarketSnapshot], []),
  'getUserPreferences' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserPreferences)],
      ['query'],
    ),
  'getUserPreferencesWithPreferences' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserPreferences)],
      [],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordAssetData' : IDL.Func([MarketData], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setUserPreferences' : IDL.Func(
      [UserPreferencesInput],
      [UserPreferences],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DirectionType = IDL.Variant({ 'up' : IDL.Null, 'down' : IDL.Null });
  const MarketData = IDL.Record({
    'direction' : DirectionType,
    'volume' : IDL.Float64,
    'price' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const UnifiedSnapshot = IDL.Record({
    'marketData' : IDL.Vec(MarketData),
    'timestamp' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'notificationsEnabled' : IDL.Bool,
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const MarketSourceResult = IDL.Record({
    'ok' : IDL.Bool,
    'body' : IDL.Text,
    'errorMessage' : IDL.Opt(IDL.Text),
  });
  const MarketSnapshot = IDL.Record({
    'binanceSpotTicker' : MarketSourceResult,
    'binanceTrades' : MarketSourceResult,
    'binanceSpotDepth' : MarketSourceResult,
    'coingeckoBTC' : MarketSourceResult,
  });
  const Theme = IDL.Variant({ 'darkNeon' : IDL.Null, 'cyberGlow' : IDL.Null });
  const UserPreferences = IDL.Record({
    'theme' : Theme,
    'language' : IDL.Text,
    'favourites' : IDL.Vec(MarketData),
    'enableAlerts' : IDL.Bool,
  });
  const UserPreferencesInput = IDL.Record({
    'theme' : Theme,
    'user' : IDL.Principal,
    'language' : IDL.Text,
    'favourites' : IDL.Vec(MarketData),
    'enableAlerts' : IDL.Bool,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'configurePollingIntervals' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'fetchAssetData' : IDL.Func([IDL.Text], [IDL.Opt(MarketData)], ['query']),
    'fetchAssetList' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'fetchBinanceFuturesAssets' : IDL.Func(
        [],
        [IDL.Opt(UnifiedSnapshot)],
        ['query'],
      ),
    'filterAssetsByDirection' : IDL.Func(
        [DirectionType],
        [IDL.Vec(MarketData)],
        ['query'],
      ),
    'getBinanceSpotDepthBTCUSDT' : IDL.Func([], [IDL.Text], []),
    'getBinanceSpotTickerBTCUSDT' : IDL.Func([], [IDL.Text], []),
    'getBinanceTradesBTCUSDT' : IDL.Func([], [IDL.Text], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCoinGeckoBTC' : IDL.Func([], [IDL.Text], []),
    'getCryptoMarketSnapshot' : IDL.Func([], [MarketSnapshot], []),
    'getUserPreferences' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserPreferences)],
        ['query'],
      ),
    'getUserPreferencesWithPreferences' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserPreferences)],
        [],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordAssetData' : IDL.Func([MarketData], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setUserPreferences' : IDL.Func(
        [UserPreferencesInput],
        [UserPreferences],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };