// Hardcoded fallback list of top-100 USD-M perpetual futures symbols
// Used when Binance API is unavailable
export const FALLBACK_FUTURES_SYMBOLS: string[] = [
  'BTCUSDT', 'ETHUSDT', 'BNBUSDT', 'SOLUSDT', 'XRPUSDT',
  'ADAUSDT', 'DOGEUSDT', 'AVAXUSDT', 'DOTUSDT', 'MATICUSDT',
  'LTCUSDT', 'LINKUSDT', 'UNIUSDT', 'ATOMUSDT', 'ETCUSDT',
  'XLMUSDT', 'BCHUSDT', 'ALGOUSDT', 'VETUSDT', 'FILUSDT',
  'TRXUSDT', 'EOSUSDT', 'AAVEUSDT', 'MKRUSDT', 'COMPUSDT',
  'SUSHIUSDT', 'YFIUSDT', 'SNXUSDT', 'CRVUSDT', 'BALUSDT',
  'RENUSDT', 'KNCUSDT', 'ZRXUSDT', 'BANDUSDT', 'STORJUSDT',
  'MANAUSDT', 'SANDUSDT', 'AXSUSDT', 'ENJUSDT', 'CHZUSDT',
  'GALAUSDT', 'FLOWUSDT', 'NEARUSDT', 'FTMUSDT', 'ONEUSDT',
  'HBARUSDT', 'EGLDUSDT', 'ICPUSDT', 'THETAUSDT', 'XTZUSDT',
  'RUNEUSDT', 'LUNAUSDT', 'COTIUSDT', 'CELOUSDT', 'KSMUSDT',
  'WAVESUSDT', 'ZECUSDT', 'DASHUSDT', 'XMRUSDT', 'NEOUSDT',
  'ONTUSDT', 'ZILUSDT', 'IOSTUSDT', 'HOTUSDT', 'BATUSDT',
  'OGNUSDT', 'SKLUSDT', 'CTKUSDT', 'REEFUSDT', 'SFPUSDT',
  'TLMUSDT', 'ALICEUSDT', 'MTLUSDT', 'NUUSDT', 'FORTHUSDT',
  'BURGERUSDT', 'BAKEUSDT', 'XVSUSDT', 'ALPACAUSDT', 'MDXUSDT',
  'DYDXUSDT', 'IOTAUSDT', 'STXUSDT', 'CKBUSDT', 'TWTUSDT',
  'LITUSDT', 'UNFIUSDT', 'WOOUSDT', 'PERPUSDT', 'RAMPUSDT',
  'SUPERUSDT', 'CFXUSDT', 'EPSUSDT', 'AUTOUSDT', 'TKOUSDT',
  'PUNDIXUSDT', 'TORNUSDT', 'KEEPUSDT', 'ERNUSDT', 'KLAYUSDT',
];
