/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserPreferences {
    theme: Theme;
    language: string;
    favourites: Array<MarketData>;
    enableAlerts: boolean;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface MarketData {
    direction: DirectionType;
    volume: number;
    price: number;
    symbol: string;
}
export interface UnifiedSnapshot {
    marketData: Array<MarketData>;
    timestamp: bigint;
}
export interface UserPreferencesInput {
    theme: Theme;
    user: Principal;
    language: string;
    favourites: Array<MarketData>;
    enableAlerts: boolean;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface MarketSourceResult {
    ok: boolean;
    body: string;
    errorMessage?: string;
}
export interface MarketSnapshot {
    binanceSpotTicker: MarketSourceResult;
    binanceTrades: MarketSourceResult;
    binanceSpotDepth: MarketSourceResult;
    coingeckoBTC: MarketSourceResult;
}
export interface UserProfile {
    notificationsEnabled: boolean;
    name: string;
    email?: string;
}
export enum DirectionType {
    up = "up",
    down = "down"
}
export enum Theme {
    darkNeon = "darkNeon",
    cyberGlow = "cyberGlow"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    configurePollingIntervals(coinsInterval: bigint, binanceInterval: bigint): Promise<void>;
    fetchAssetData(symbol: string): Promise<MarketData | null>;
    fetchAssetList(): Promise<Array<string>>;
    fetchBinanceFuturesAssets(): Promise<UnifiedSnapshot | null>;
    filterAssetsByDirection(direction: DirectionType): Promise<Array<MarketData>>;
    getBinanceSpotDepthBTCUSDT(): Promise<string>;
    getBinanceSpotTickerBTCUSDT(): Promise<string>;
    getBinanceTradesBTCUSDT(): Promise<string>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCoinGeckoBTC(): Promise<string>;
    getCryptoMarketSnapshot(): Promise<MarketSnapshot>;
    getUserPreferences(user: Principal): Promise<UserPreferences | null>;
    getUserPreferencesWithPreferences(user: Principal): Promise<UserPreferences | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    recordAssetData(data: MarketData): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setUserPreferences(input: UserPreferencesInput): Promise<UserPreferences>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { DirectionType as _DirectionType, MarketData as _MarketData, MarketSnapshot as _MarketSnapshot, MarketSourceResult as _MarketSourceResult, Theme as _Theme, UnifiedSnapshot as _UnifiedSnapshot, UserPreferences as _UserPreferences, UserPreferencesInput as _UserPreferencesInput, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async configurePollingIntervals(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.configurePollingIntervals(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.configurePollingIntervals(arg0, arg1);
            return result;
        }
    }
    async fetchAssetData(arg0: string): Promise<MarketData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchAssetData(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchAssetData(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async fetchAssetList(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchAssetList();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchAssetList();
            return result;
        }
    }
    async fetchBinanceFuturesAssets(): Promise<UnifiedSnapshot | null> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchBinanceFuturesAssets();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchBinanceFuturesAssets();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterAssetsByDirection(arg0: DirectionType): Promise<Array<MarketData>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterAssetsByDirection(to_candid_DirectionType_n12(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterAssetsByDirection(to_candid_DirectionType_n12(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBinanceSpotDepthBTCUSDT(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getBinanceSpotDepthBTCUSDT();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBinanceSpotDepthBTCUSDT();
            return result;
        }
    }
    async getBinanceSpotTickerBTCUSDT(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getBinanceSpotTickerBTCUSDT();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBinanceSpotTickerBTCUSDT();
            return result;
        }
    }
    async getBinanceTradesBTCUSDT(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getBinanceTradesBTCUSDT();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBinanceTradesBTCUSDT();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoinGeckoBTC(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoinGeckoBTC();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoinGeckoBTC();
            return result;
        }
    }
    async getCryptoMarketSnapshot(): Promise<MarketSnapshot> {
        if (this.processError) {
            try {
                const result = await this.actor.getCryptoMarketSnapshot();
                return from_candid_MarketSnapshot_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCryptoMarketSnapshot();
            return from_candid_MarketSnapshot_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserPreferences(arg0: Principal): Promise<UserPreferences | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPreferences(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPreferences(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserPreferencesWithPreferences(arg0: Principal): Promise<UserPreferences | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPreferencesWithPreferences(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPreferencesWithPreferences(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async recordAssetData(arg0: MarketData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordAssetData(to_candid_MarketData_n29(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordAssetData(to_candid_MarketData_n29(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n31(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n31(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setUserPreferences(arg0: UserPreferencesInput): Promise<UserPreferences> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserPreferences(to_candid_UserPreferencesInput_n33(this._uploadFile, this._downloadFile, arg0));
                return from_candid_UserPreferences_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserPreferences(to_candid_UserPreferencesInput_n33(this._uploadFile, this._downloadFile, arg0));
            return from_candid_UserPreferences_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_DirectionType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DirectionType): DirectionType {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_MarketData_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MarketData): MarketData {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_MarketSnapshot_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MarketSnapshot): MarketSnapshot {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_MarketSourceResult_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MarketSourceResult): MarketSourceResult {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Theme_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Theme): Theme {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UnifiedSnapshot_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UnifiedSnapshot): UnifiedSnapshot {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserPreferences_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserPreferences): UserPreferences {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserPreferences]): UserPreferences | null {
    return value.length === 0 ? null : from_candid_UserPreferences_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MarketData]): MarketData | null {
    return value.length === 0 ? null : from_candid_MarketData_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UnifiedSnapshot]): UnifiedSnapshot | null {
    return value.length === 0 ? null : from_candid_UnifiedSnapshot_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    marketData: Array<_MarketData>;
    timestamp: bigint;
}): {
    marketData: Array<MarketData>;
    timestamp: bigint;
} {
    return {
        marketData: from_candid_vec_n11(_uploadFile, _downloadFile, value.marketData),
        timestamp: value.timestamp
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notificationsEnabled: boolean;
    name: string;
    email: [] | [string];
}): {
    notificationsEnabled: boolean;
    name: string;
    email?: string;
} {
    return {
        notificationsEnabled: value.notificationsEnabled,
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.email))
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    binanceSpotTicker: _MarketSourceResult;
    binanceTrades: _MarketSourceResult;
    binanceSpotDepth: _MarketSourceResult;
    coingeckoBTC: _MarketSourceResult;
}): {
    binanceSpotTicker: MarketSourceResult;
    binanceTrades: MarketSourceResult;
    binanceSpotDepth: MarketSourceResult;
    coingeckoBTC: MarketSourceResult;
} {
    return {
        binanceSpotTicker: from_candid_MarketSourceResult_n22(_uploadFile, _downloadFile, value.binanceSpotTicker),
        binanceTrades: from_candid_MarketSourceResult_n22(_uploadFile, _downloadFile, value.binanceTrades),
        binanceSpotDepth: from_candid_MarketSourceResult_n22(_uploadFile, _downloadFile, value.binanceSpotDepth),
        coingeckoBTC: from_candid_MarketSourceResult_n22(_uploadFile, _downloadFile, value.coingeckoBTC)
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
    body: string;
    errorMessage: [] | [string];
}): {
    ok: boolean;
    body: string;
    errorMessage?: string;
} {
    return {
        ok: value.ok,
        body: value.body,
        errorMessage: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.errorMessage))
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    theme: _Theme;
    language: string;
    favourites: Array<_MarketData>;
    enableAlerts: boolean;
}): {
    theme: Theme;
    language: string;
    favourites: Array<MarketData>;
    enableAlerts: boolean;
} {
    return {
        theme: from_candid_Theme_n27(_uploadFile, _downloadFile, value.theme),
        language: value.language,
        favourites: from_candid_vec_n11(_uploadFile, _downloadFile, value.favourites),
        enableAlerts: value.enableAlerts
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    direction: _DirectionType;
    volume: number;
    price: number;
    symbol: string;
}): {
    direction: DirectionType;
    volume: number;
    price: number;
    symbol: string;
} {
    return {
        direction: from_candid_DirectionType_n6(_uploadFile, _downloadFile, value.direction),
        volume: value.volume,
        price: value.price,
        symbol: value.symbol
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    darkNeon: null;
} | {
    cyberGlow: null;
}): Theme {
    return "darkNeon" in value ? Theme.darkNeon : "cyberGlow" in value ? Theme.cyberGlow : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    up: null;
} | {
    down: null;
}): DirectionType {
    return "up" in value ? DirectionType.up : "down" in value ? DirectionType.down : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MarketData>): Array<MarketData> {
    return value.map((x)=>from_candid_MarketData_n4(_uploadFile, _downloadFile, x));
}
function to_candid_DirectionType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DirectionType): _DirectionType {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_MarketData_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MarketData): _MarketData {
    return to_candid_record_n30(_uploadFile, _downloadFile, value);
}
function to_candid_Theme_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Theme): _Theme {
    return to_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function to_candid_UserPreferencesInput_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserPreferencesInput): _UserPreferencesInput {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    direction: DirectionType;
    volume: number;
    price: number;
    symbol: string;
}): {
    direction: _DirectionType;
    volume: number;
    price: number;
    symbol: string;
} {
    return {
        direction: to_candid_DirectionType_n12(_uploadFile, _downloadFile, value.direction),
        volume: value.volume,
        price: value.price,
        symbol: value.symbol
    };
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notificationsEnabled: boolean;
    name: string;
    email?: string;
}): {
    notificationsEnabled: boolean;
    name: string;
    email: [] | [string];
} {
    return {
        notificationsEnabled: value.notificationsEnabled,
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none()
    };
}
function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    theme: Theme;
    user: Principal;
    language: string;
    favourites: Array<MarketData>;
    enableAlerts: boolean;
}): {
    theme: _Theme;
    user: Principal;
    language: string;
    favourites: Array<_MarketData>;
    enableAlerts: boolean;
} {
    return {
        theme: to_candid_Theme_n35(_uploadFile, _downloadFile, value.theme),
        user: value.user,
        language: value.language,
        favourites: to_candid_vec_n37(_uploadFile, _downloadFile, value.favourites),
        enableAlerts: value.enableAlerts
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DirectionType): {
    up: null;
} | {
    down: null;
} {
    return value == DirectionType.up ? {
        up: null
    } : value == DirectionType.down ? {
        down: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Theme): {
    darkNeon: null;
} | {
    cyberGlow: null;
} {
    return value == Theme.darkNeon ? {
        darkNeon: null
    } : value == Theme.cyberGlow ? {
        cyberGlow: null
    } : value;
}
function to_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<MarketData>): Array<_MarketData> {
    return value.map((x)=>to_candid_MarketData_n29(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
